"""kitchen finance automation

Revision ID: 5b230780f4f2
Revises: 0015_core_domain_intelligence
Create Date: 2026-09-21 22:05:37.210505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b230780f4f2'
down_revision: Union[str, Sequence[str], None] = '0015_core_domain_intelligence'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooking_techniques',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_cooking_technique_key')
    )
    op.create_index(op.f('ix_cooking_techniques_user_id'), 'cooking_techniques', ['user_id'], unique=False)
    op.create_table('finance_categories',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['finance_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_finance_category_user_name')
    )
    op.create_index(op.f('ix_finance_categories_active'), 'finance_categories', ['active'], unique=False)
    op.create_index(op.f('ix_finance_categories_kind'), 'finance_categories', ['kind'], unique=False)
    op.create_index(op.f('ix_finance_categories_parent_id'), 'finance_categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_finance_categories_user_id'), 'finance_categories', ['user_id'], unique=False)
    op.create_table('finance_import_batches',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=240), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('mapping_json', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('ready_count', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_hash', name='uq_finance_import_batch_hash')
    )
    op.create_index(op.f('ix_finance_import_batches_content_hash'), 'finance_import_batches', ['content_hash'], unique=False)
    op.create_index(op.f('ix_finance_import_batches_status'), 'finance_import_batches', ['status'], unique=False)
    op.create_index(op.f('ix_finance_import_batches_user_id'), 'finance_import_batches', ['user_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('storage_provider', sa.String(length=40), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('generation_version', sa.String(length=80), nullable=True),
    sa.Column('linked_entity_type', sa.String(length=80), nullable=True),
    sa.Column('linked_entity_id', sa.String(length=36), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'content_hash', name='uq_media_asset_user_kind_hash')
    )
    op.create_index(op.f('ix_media_assets_content_hash'), 'media_assets', ['content_hash'], unique=False)
    op.create_index(op.f('ix_media_assets_deleted_at'), 'media_assets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_media_assets_kind'), 'media_assets', ['kind'], unique=False)
    op.create_index(op.f('ix_media_assets_linked_entity_id'), 'media_assets', ['linked_entity_id'], unique=False)
    op.create_index(op.f('ix_media_assets_linked_entity_type'), 'media_assets', ['linked_entity_type'], unique=False)
    op.create_index(op.f('ix_media_assets_source'), 'media_assets', ['source'], unique=False)
    op.create_index(op.f('ix_media_assets_user_id'), 'media_assets', ['user_id'], unique=False)
    op.create_table('cooking_competencies',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('technique_id', sa.String(length=36), nullable=False),
    sa.Column('estimated_level', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('successful_repetitions', sa.Integer(), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['technique_id'], ['cooking_techniques.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'technique_id', name='uq_cooking_competency')
    )
    op.create_index(op.f('ix_cooking_competencies_technique_id'), 'cooking_competencies', ['technique_id'], unique=False)
    op.create_index(op.f('ix_cooking_competencies_user_id'), 'cooking_competencies', ['user_id'], unique=False)
    op.create_table('finance_budgets',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('period', sa.String(length=40), nullable=False),
    sa.Column('month_start', sa.Date(), nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['finance_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', 'month_start', name='uq_finance_budget_period')
    )
    op.create_index(op.f('ix_finance_budgets_active'), 'finance_budgets', ['active'], unique=False)
    op.create_index(op.f('ix_finance_budgets_category_id'), 'finance_budgets', ['category_id'], unique=False)
    op.create_index(op.f('ix_finance_budgets_month_start'), 'finance_budgets', ['month_start'], unique=False)
    op.create_index(op.f('ix_finance_budgets_user_id'), 'finance_budgets', ['user_id'], unique=False)
    op.create_table('finance_merchants',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('normalized_name', sa.String(length=180), nullable=False),
    sa.Column('default_category_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['default_category_id'], ['finance_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'normalized_name', name='uq_finance_merchant_normalized')
    )
    op.create_index(op.f('ix_finance_merchants_default_category_id'), 'finance_merchants', ['default_category_id'], unique=False)
    op.create_index(op.f('ix_finance_merchants_normalized_name'), 'finance_merchants', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_finance_merchants_user_id'), 'finance_merchants', ['user_id'], unique=False)
    op.create_table('kitchen_ingredient_aliases',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=180), nullable=False),
    sa.Column('normalized_alias', sa.String(length=180), nullable=False),
    sa.Column('merchant', sa.String(length=180), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['kitchen_ingredients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'normalized_alias', 'merchant', name='uq_kitchen_ingredient_alias')
    )
    op.create_index(op.f('ix_kitchen_ingredient_aliases_ingredient_id'), 'kitchen_ingredient_aliases', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_kitchen_ingredient_aliases_merchant'), 'kitchen_ingredient_aliases', ['merchant'], unique=False)
    op.create_index(op.f('ix_kitchen_ingredient_aliases_normalized_alias'), 'kitchen_ingredient_aliases', ['normalized_alias'], unique=False)
    op.create_index(op.f('ix_kitchen_ingredient_aliases_user_id'), 'kitchen_ingredient_aliases', ['user_id'], unique=False)
    op.create_table('kitchen_recipe_techniques',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('technique_id', sa.String(length=36), nullable=False),
    sa.Column('required_level', sa.Float(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['kitchen_recipes.id'], ),
    sa.ForeignKeyConstraint(['technique_id'], ['cooking_techniques.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'technique_id', name='uq_recipe_technique')
    )
    op.create_index(op.f('ix_kitchen_recipe_techniques_recipe_id'), 'kitchen_recipe_techniques', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_kitchen_recipe_techniques_technique_id'), 'kitchen_recipe_techniques', ['technique_id'], unique=False)
    op.create_index(op.f('ix_kitchen_recipe_techniques_user_id'), 'kitchen_recipe_techniques', ['user_id'], unique=False)
    op.create_table('finance_import_rows',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('merchant_raw', sa.String(length=240), nullable=True),
    sa.Column('merchant_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('external_id', sa.String(length=180), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['finance_import_batches.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['finance_categories.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['finance_merchants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'row_number', name='uq_finance_import_row_number')
    )
    op.create_index(op.f('ix_finance_import_rows_batch_id'), 'finance_import_rows', ['batch_id'], unique=False)
    op.create_index(op.f('ix_finance_import_rows_category_id'), 'finance_import_rows', ['category_id'], unique=False)
    op.create_index(op.f('ix_finance_import_rows_direction'), 'finance_import_rows', ['direction'], unique=False)
    op.create_index(op.f('ix_finance_import_rows_fingerprint'), 'finance_import_rows', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_finance_import_rows_merchant_id'), 'finance_import_rows', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_finance_import_rows_occurred_on'), 'finance_import_rows', ['occurred_on'], unique=False)
    op.create_index(op.f('ix_finance_import_rows_review_required'), 'finance_import_rows', ['review_required'], unique=False)
    op.create_index(op.f('ix_finance_import_rows_status'), 'finance_import_rows', ['status'], unique=False)
    op.create_index(op.f('ix_finance_import_rows_user_id'), 'finance_import_rows', ['user_id'], unique=False)
    op.create_table('finance_merchant_aliases',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=240), nullable=False),
    sa.Column('normalized_alias', sa.String(length=240), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['finance_merchants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'normalized_alias', name='uq_finance_merchant_alias')
    )
    op.create_index(op.f('ix_finance_merchant_aliases_merchant_id'), 'finance_merchant_aliases', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_finance_merchant_aliases_normalized_alias'), 'finance_merchant_aliases', ['normalized_alias'], unique=False)
    op.create_index(op.f('ix_finance_merchant_aliases_user_id'), 'finance_merchant_aliases', ['user_id'], unique=False)
    op.create_table('finance_recurring_expenses',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('typical_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('next_expected_on', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['finance_categories.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['finance_merchants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'merchant_id', name='uq_finance_recurring_merchant')
    )
    op.create_index(op.f('ix_finance_recurring_expenses_category_id'), 'finance_recurring_expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_finance_recurring_expenses_merchant_id'), 'finance_recurring_expenses', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_finance_recurring_expenses_next_expected_on'), 'finance_recurring_expenses', ['next_expected_on'], unique=False)
    op.create_index(op.f('ix_finance_recurring_expenses_status'), 'finance_recurring_expenses', ['status'], unique=False)
    op.create_index(op.f('ix_finance_recurring_expenses_user_id'), 'finance_recurring_expenses', ['user_id'], unique=False)
    op.create_table('receipt_imports',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('merchant_raw', sa.String(length=240), nullable=True),
    sa.Column('merchant_id', sa.String(length=36), nullable=True),
    sa.Column('transaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_provider', sa.String(length=80), nullable=True),
    sa.Column('extraction_model', sa.String(length=160), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('finance_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['finance_merchants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_id', name='uq_receipt_import_asset')
    )
    op.create_index(op.f('ix_receipt_imports_asset_id'), 'receipt_imports', ['asset_id'], unique=False)
    op.create_index(op.f('ix_receipt_imports_finance_transaction_id'), 'receipt_imports', ['finance_transaction_id'], unique=False)
    op.create_index(op.f('ix_receipt_imports_merchant_id'), 'receipt_imports', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_receipt_imports_status'), 'receipt_imports', ['status'], unique=False)
    op.create_index(op.f('ix_receipt_imports_transaction_at'), 'receipt_imports', ['transaction_at'], unique=False)
    op.create_index(op.f('ix_receipt_imports_user_id'), 'receipt_imports', ['user_id'], unique=False)
    op.create_table('finance_transactions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('merchant_raw', sa.String(length=240), nullable=True),
    sa.Column('merchant_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('external_id', sa.String(length=180), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('receipt_import_id', sa.String(length=36), nullable=True),
    sa.Column('import_batch_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['finance_categories.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['finance_import_batches.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['finance_merchants.id'], ),
    sa.ForeignKeyConstraint(['receipt_import_id'], ['receipt_imports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fingerprint', name='uq_finance_transaction_fingerprint')
    )
    op.create_index(op.f('ix_finance_transactions_category_id'), 'finance_transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_currency'), 'finance_transactions', ['currency'], unique=False)
    op.create_index(op.f('ix_finance_transactions_direction'), 'finance_transactions', ['direction'], unique=False)
    op.create_index(op.f('ix_finance_transactions_external_id'), 'finance_transactions', ['external_id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_fingerprint'), 'finance_transactions', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_finance_transactions_import_batch_id'), 'finance_transactions', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_merchant_id'), 'finance_transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_occurred_on'), 'finance_transactions', ['occurred_on'], unique=False)
    op.create_index(op.f('ix_finance_transactions_receipt_import_id'), 'finance_transactions', ['receipt_import_id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_source'), 'finance_transactions', ['source'], unique=False)
    op.create_index(op.f('ix_finance_transactions_user_id'), 'finance_transactions', ['user_id'], unique=False)
    op.create_table('kitchen_meal_plans',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=True),
    sa.Column('recommendation_option_id', sa.String(length=36), nullable=True),
    sa.Column('planned_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meal_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('planned_servings', sa.Float(), nullable=False),
    sa.Column('nutrition_snapshot', sa.JSON(), nullable=False),
    sa.Column('shopping_action_id', sa.String(length=36), nullable=True),
    sa.Column('cooking_action_id', sa.String(length=36), nullable=True),
    sa.Column('meal_history_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cooking_action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['kitchen_recipes.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['recommendation_option_id'], ['recommendation_options.id'], ),
    sa.ForeignKeyConstraint(['shopping_action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_kitchen_meal_plan_idempotency')
    )
    op.create_index(op.f('ix_kitchen_meal_plans_cooking_action_id'), 'kitchen_meal_plans', ['cooking_action_id'], unique=False)
    op.create_index(op.f('ix_kitchen_meal_plans_idempotency_key'), 'kitchen_meal_plans', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_kitchen_meal_plans_meal_history_id'), 'kitchen_meal_plans', ['meal_history_id'], unique=False)
    op.create_index(op.f('ix_kitchen_meal_plans_planned_for'), 'kitchen_meal_plans', ['planned_for'], unique=False)
    op.create_index(op.f('ix_kitchen_meal_plans_recipe_id'), 'kitchen_meal_plans', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_kitchen_meal_plans_recommendation_id'), 'kitchen_meal_plans', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_kitchen_meal_plans_recommendation_option_id'), 'kitchen_meal_plans', ['recommendation_option_id'], unique=False)
    op.create_index(op.f('ix_kitchen_meal_plans_shopping_action_id'), 'kitchen_meal_plans', ['shopping_action_id'], unique=False)
    op.create_index(op.f('ix_kitchen_meal_plans_status'), 'kitchen_meal_plans', ['status'], unique=False)
    op.create_index(op.f('ix_kitchen_meal_plans_user_id'), 'kitchen_meal_plans', ['user_id'], unique=False)
    op.create_table('cooking_competency_evidence',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('competency_id', sa.String(length=36), nullable=False),
    sa.Column('meal_history_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('successful', sa.Boolean(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['cooking_competencies.id'], ),
    sa.ForeignKeyConstraint(['meal_history_id'], ['kitchen_meal_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_cooking_evidence_idempotency')
    )
    op.create_index(op.f('ix_cooking_competency_evidence_competency_id'), 'cooking_competency_evidence', ['competency_id'], unique=False)
    op.create_index(op.f('ix_cooking_competency_evidence_idempotency_key'), 'cooking_competency_evidence', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_cooking_competency_evidence_meal_history_id'), 'cooking_competency_evidence', ['meal_history_id'], unique=False)
    op.create_index(op.f('ix_cooking_competency_evidence_user_id'), 'cooking_competency_evidence', ['user_id'], unique=False)
    op.create_table('kitchen_meal_feedback',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('meal_history_id', sa.String(length=36), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('structured_json', sa.JSON(), nullable=False),
    sa.Column('interpretation_status', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_history_id'], ['kitchen_meal_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_kitchen_meal_feedback_idempotency')
    )
    op.create_index(op.f('ix_kitchen_meal_feedback_idempotency_key'), 'kitchen_meal_feedback', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_kitchen_meal_feedback_interpretation_status'), 'kitchen_meal_feedback', ['interpretation_status'], unique=False)
    op.create_index(op.f('ix_kitchen_meal_feedback_meal_history_id'), 'kitchen_meal_feedback', ['meal_history_id'], unique=False)
    op.create_index(op.f('ix_kitchen_meal_feedback_user_id'), 'kitchen_meal_feedback', ['user_id'], unique=False)
    op.create_table('receipt_lines',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('receipt_import_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=180), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('confidence_name', sa.Float(), nullable=False),
    sa.Column('confidence_quantity', sa.Float(), nullable=False),
    sa.Column('confidence_price', sa.Float(), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('ingredient_id', sa.String(length=36), nullable=True),
    sa.Column('inventory_item_id', sa.String(length=36), nullable=True),
    sa.Column('inventory_lot_id', sa.String(length=36), nullable=True),
    sa.Column('shopping_need_item_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['kitchen_ingredients.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['kitchen_inventory_items.id'], ),
    sa.ForeignKeyConstraint(['inventory_lot_id'], ['kitchen_inventory_lots.id'], ),
    sa.ForeignKeyConstraint(['receipt_import_id'], ['receipt_imports.id'], ),
    sa.ForeignKeyConstraint(['shopping_need_item_id'], ['kitchen_shopping_need_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_import_id', 'line_number', name='uq_receipt_line_number')
    )
    op.create_index(op.f('ix_receipt_lines_category'), 'receipt_lines', ['category'], unique=False)
    op.create_index(op.f('ix_receipt_lines_ingredient_id'), 'receipt_lines', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_receipt_lines_inventory_item_id'), 'receipt_lines', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_receipt_lines_inventory_lot_id'), 'receipt_lines', ['inventory_lot_id'], unique=False)
    op.create_index(op.f('ix_receipt_lines_normalized_name'), 'receipt_lines', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_receipt_lines_receipt_import_id'), 'receipt_lines', ['receipt_import_id'], unique=False)
    op.create_index(op.f('ix_receipt_lines_review_required'), 'receipt_lines', ['review_required'], unique=False)
    op.create_index(op.f('ix_receipt_lines_shopping_need_item_id'), 'receipt_lines', ['shopping_need_item_id'], unique=False)
    op.create_index(op.f('ix_receipt_lines_user_id'), 'receipt_lines', ['user_id'], unique=False)
    op.add_column('kitchen_ingredients', sa.Column('normalized_name', sa.String(length=180), nullable=True))
    op.add_column('kitchen_ingredients', sa.Column('category', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_kitchen_ingredients_category'), 'kitchen_ingredients', ['category'], unique=False)
    op.create_index(op.f('ix_kitchen_ingredients_normalized_name'), 'kitchen_ingredients', ['normalized_name'], unique=False)
    op.create_unique_constraint('uq_kitchen_ingredient_normalized', 'kitchen_ingredients', ['user_id', 'normalized_name'])
    op.add_column('kitchen_inventory_items', sa.Column('ingredient_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_kitchen_inventory_items_ingredient_id'), 'kitchen_inventory_items', ['ingredient_id'], unique=False)
    op.create_foreign_key('fk_kitchen_inventory_items_ingredient_id', 'kitchen_inventory_items', 'kitchen_ingredients', ['ingredient_id'], ['id'])
    op.add_column('kitchen_inventory_lots', sa.Column('source_reference_type', sa.String(length=80), nullable=True))
    op.add_column('kitchen_inventory_lots', sa.Column('source_reference_id', sa.String(length=36), nullable=True))
    op.add_column('kitchen_inventory_lots', sa.Column('confidence', sa.Float(), nullable=True))
    op.create_index(op.f('ix_kitchen_inventory_lots_source_reference_id'), 'kitchen_inventory_lots', ['source_reference_id'], unique=False)
    op.create_index(op.f('ix_kitchen_inventory_lots_source_reference_type'), 'kitchen_inventory_lots', ['source_reference_type'], unique=False)
    op.add_column('kitchen_meal_history', sa.Column('meal_plan_id', sa.String(length=36), nullable=True))
    op.add_column('kitchen_meal_history', sa.Column('recommendation_id', sa.String(length=36), nullable=True))
    op.add_column('kitchen_meal_history', sa.Column('recommendation_option_id', sa.String(length=36), nullable=True))
    op.add_column('kitchen_meal_history', sa.Column('idempotency_key', sa.String(length=160), nullable=True))
    op.create_index(op.f('ix_kitchen_meal_history_idempotency_key'), 'kitchen_meal_history', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_kitchen_meal_history_meal_plan_id'), 'kitchen_meal_history', ['meal_plan_id'], unique=False)
    op.create_index(op.f('ix_kitchen_meal_history_recommendation_id'), 'kitchen_meal_history', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_kitchen_meal_history_recommendation_option_id'), 'kitchen_meal_history', ['recommendation_option_id'], unique=False)
    op.create_unique_constraint('uq_kitchen_meal_history_idempotency', 'kitchen_meal_history', ['user_id', 'idempotency_key'])
    op.create_foreign_key('fk_kitchen_meal_history_recommendation_id', 'kitchen_meal_history', 'recommendations', ['recommendation_id'], ['id'])
    op.create_foreign_key('fk_kitchen_meal_history_recommendation_option_id', 'kitchen_meal_history', 'recommendation_options', ['recommendation_option_id'], ['id'])
    op.create_foreign_key('fk_kitchen_meal_history_meal_plan_id', 'kitchen_meal_history', 'kitchen_meal_plans', ['meal_plan_id'], ['id'])
    op.add_column('kitchen_recipe_ingredients', sa.Column('ingredient_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_kitchen_recipe_ingredients_ingredient_id'), 'kitchen_recipe_ingredients', ['ingredient_id'], unique=False)
    op.create_foreign_key('fk_kitchen_recipe_ingredients_ingredient_id', 'kitchen_recipe_ingredients', 'kitchen_ingredients', ['ingredient_id'], ['id'])
    op.add_column('kitchen_recipes', sa.Column('steps_json', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.alter_column('kitchen_recipes', 'steps_json', server_default=None)
    op.add_column('kitchen_shopping_need_items', sa.Column('priority_class', sa.String(length=40), nullable=False, server_default='optional'))
    op.add_column('kitchen_shopping_need_items', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('kitchen_shopping_need_items', sa.Column('source_type', sa.String(length=80), nullable=True))
    op.add_column('kitchen_shopping_need_items', sa.Column('source_id', sa.String(length=36), nullable=True))
    op.add_column('kitchen_shopping_need_items', sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('kitchen_shopping_need_items', sa.Column('purchased_quantity', sa.Float(), nullable=False, server_default='0'))
    op.add_column('kitchen_shopping_need_items', sa.Column('status', sa.String(length=40), nullable=False, server_default='needed'))
    op.alter_column('kitchen_shopping_need_items', 'priority_class', server_default=None)
    op.alter_column('kitchen_shopping_need_items', 'purchased_quantity', server_default=None)
    op.alter_column('kitchen_shopping_need_items', 'status', server_default=None)
    op.create_index(op.f('ix_kitchen_shopping_need_items_priority_class'), 'kitchen_shopping_need_items', ['priority_class'], unique=False)
    op.create_index(op.f('ix_kitchen_shopping_need_items_source_id'), 'kitchen_shopping_need_items', ['source_id'], unique=False)
    op.create_index(op.f('ix_kitchen_shopping_need_items_source_type'), 'kitchen_shopping_need_items', ['source_type'], unique=False)
    op.create_index(op.f('ix_kitchen_shopping_need_items_status'), 'kitchen_shopping_need_items', ['status'], unique=False)
    op.add_column('kitchen_shopping_needs', sa.Column('meal_plan_id', sa.String(length=36), nullable=True))
    op.add_column('kitchen_shopping_needs', sa.Column('action_id', sa.String(length=36), nullable=True))
    op.add_column('kitchen_shopping_needs', sa.Column('estimated_total', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('kitchen_shopping_needs', sa.Column('currency', sa.String(length=3), nullable=False, server_default='EUR'))
    op.alter_column('kitchen_shopping_needs', 'currency', server_default=None)
    op.add_column('kitchen_shopping_needs', sa.Column('idempotency_key', sa.String(length=160), nullable=True))
    op.create_index(op.f('ix_kitchen_shopping_needs_action_id'), 'kitchen_shopping_needs', ['action_id'], unique=False)
    op.create_index(op.f('ix_kitchen_shopping_needs_idempotency_key'), 'kitchen_shopping_needs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_kitchen_shopping_needs_meal_plan_id'), 'kitchen_shopping_needs', ['meal_plan_id'], unique=False)
    op.create_unique_constraint('uq_kitchen_shopping_need_idempotency', 'kitchen_shopping_needs', ['user_id', 'idempotency_key'])
    op.create_foreign_key('fk_kitchen_shopping_needs_meal_plan_id', 'kitchen_shopping_needs', 'kitchen_meal_plans', ['meal_plan_id'], ['id'])
    op.create_foreign_key('fk_kitchen_shopping_needs_action_id', 'kitchen_shopping_needs', 'actions', ['action_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_kitchen_shopping_needs_action_id', 'kitchen_shopping_needs', type_='foreignkey')
    op.drop_constraint('fk_kitchen_shopping_needs_meal_plan_id', 'kitchen_shopping_needs', type_='foreignkey')
    op.drop_constraint('uq_kitchen_shopping_need_idempotency', 'kitchen_shopping_needs', type_='unique')
    op.drop_index(op.f('ix_kitchen_shopping_needs_meal_plan_id'), table_name='kitchen_shopping_needs')
    op.drop_index(op.f('ix_kitchen_shopping_needs_idempotency_key'), table_name='kitchen_shopping_needs')
    op.drop_index(op.f('ix_kitchen_shopping_needs_action_id'), table_name='kitchen_shopping_needs')
    op.drop_column('kitchen_shopping_needs', 'idempotency_key')
    op.drop_column('kitchen_shopping_needs', 'currency')
    op.drop_column('kitchen_shopping_needs', 'estimated_total')
    op.drop_column('kitchen_shopping_needs', 'action_id')
    op.drop_column('kitchen_shopping_needs', 'meal_plan_id')
    op.drop_index(op.f('ix_kitchen_shopping_need_items_status'), table_name='kitchen_shopping_need_items')
    op.drop_index(op.f('ix_kitchen_shopping_need_items_source_type'), table_name='kitchen_shopping_need_items')
    op.drop_index(op.f('ix_kitchen_shopping_need_items_source_id'), table_name='kitchen_shopping_need_items')
    op.drop_index(op.f('ix_kitchen_shopping_need_items_priority_class'), table_name='kitchen_shopping_need_items')
    op.drop_column('kitchen_shopping_need_items', 'status')
    op.drop_column('kitchen_shopping_need_items', 'purchased_quantity')
    op.drop_column('kitchen_shopping_need_items', 'estimated_cost')
    op.drop_column('kitchen_shopping_need_items', 'source_id')
    op.drop_column('kitchen_shopping_need_items', 'source_type')
    op.drop_column('kitchen_shopping_need_items', 'reason')
    op.drop_column('kitchen_shopping_need_items', 'priority_class')
    op.drop_column('kitchen_recipes', 'steps_json')
    op.drop_constraint('fk_kitchen_recipe_ingredients_ingredient_id', 'kitchen_recipe_ingredients', type_='foreignkey')
    op.drop_index(op.f('ix_kitchen_recipe_ingredients_ingredient_id'), table_name='kitchen_recipe_ingredients')
    op.drop_column('kitchen_recipe_ingredients', 'ingredient_id')
    op.drop_constraint('fk_kitchen_meal_history_meal_plan_id', 'kitchen_meal_history', type_='foreignkey')
    op.drop_constraint('fk_kitchen_meal_history_recommendation_option_id', 'kitchen_meal_history', type_='foreignkey')
    op.drop_constraint('fk_kitchen_meal_history_recommendation_id', 'kitchen_meal_history', type_='foreignkey')
    op.drop_constraint('uq_kitchen_meal_history_idempotency', 'kitchen_meal_history', type_='unique')
    op.drop_index(op.f('ix_kitchen_meal_history_recommendation_option_id'), table_name='kitchen_meal_history')
    op.drop_index(op.f('ix_kitchen_meal_history_recommendation_id'), table_name='kitchen_meal_history')
    op.drop_index(op.f('ix_kitchen_meal_history_meal_plan_id'), table_name='kitchen_meal_history')
    op.drop_index(op.f('ix_kitchen_meal_history_idempotency_key'), table_name='kitchen_meal_history')
    op.drop_column('kitchen_meal_history', 'idempotency_key')
    op.drop_column('kitchen_meal_history', 'recommendation_option_id')
    op.drop_column('kitchen_meal_history', 'recommendation_id')
    op.drop_column('kitchen_meal_history', 'meal_plan_id')
    op.drop_index(op.f('ix_kitchen_inventory_lots_source_reference_type'), table_name='kitchen_inventory_lots')
    op.drop_index(op.f('ix_kitchen_inventory_lots_source_reference_id'), table_name='kitchen_inventory_lots')
    op.drop_column('kitchen_inventory_lots', 'confidence')
    op.drop_column('kitchen_inventory_lots', 'source_reference_id')
    op.drop_column('kitchen_inventory_lots', 'source_reference_type')
    op.drop_constraint('fk_kitchen_inventory_items_ingredient_id', 'kitchen_inventory_items', type_='foreignkey')
    op.drop_index(op.f('ix_kitchen_inventory_items_ingredient_id'), table_name='kitchen_inventory_items')
    op.drop_column('kitchen_inventory_items', 'ingredient_id')
    op.drop_constraint('uq_kitchen_ingredient_normalized', 'kitchen_ingredients', type_='unique')
    op.drop_index(op.f('ix_kitchen_ingredients_normalized_name'), table_name='kitchen_ingredients')
    op.drop_index(op.f('ix_kitchen_ingredients_category'), table_name='kitchen_ingredients')
    op.drop_column('kitchen_ingredients', 'category')
    op.drop_column('kitchen_ingredients', 'normalized_name')
    op.drop_index(op.f('ix_receipt_lines_user_id'), table_name='receipt_lines')
    op.drop_index(op.f('ix_receipt_lines_shopping_need_item_id'), table_name='receipt_lines')
    op.drop_index(op.f('ix_receipt_lines_review_required'), table_name='receipt_lines')
    op.drop_index(op.f('ix_receipt_lines_receipt_import_id'), table_name='receipt_lines')
    op.drop_index(op.f('ix_receipt_lines_normalized_name'), table_name='receipt_lines')
    op.drop_index(op.f('ix_receipt_lines_inventory_lot_id'), table_name='receipt_lines')
    op.drop_index(op.f('ix_receipt_lines_inventory_item_id'), table_name='receipt_lines')
    op.drop_index(op.f('ix_receipt_lines_ingredient_id'), table_name='receipt_lines')
    op.drop_index(op.f('ix_receipt_lines_category'), table_name='receipt_lines')
    op.drop_table('receipt_lines')
    op.drop_index(op.f('ix_kitchen_meal_feedback_user_id'), table_name='kitchen_meal_feedback')
    op.drop_index(op.f('ix_kitchen_meal_feedback_meal_history_id'), table_name='kitchen_meal_feedback')
    op.drop_index(op.f('ix_kitchen_meal_feedback_interpretation_status'), table_name='kitchen_meal_feedback')
    op.drop_index(op.f('ix_kitchen_meal_feedback_idempotency_key'), table_name='kitchen_meal_feedback')
    op.drop_table('kitchen_meal_feedback')
    op.drop_index(op.f('ix_cooking_competency_evidence_user_id'), table_name='cooking_competency_evidence')
    op.drop_index(op.f('ix_cooking_competency_evidence_meal_history_id'), table_name='cooking_competency_evidence')
    op.drop_index(op.f('ix_cooking_competency_evidence_idempotency_key'), table_name='cooking_competency_evidence')
    op.drop_index(op.f('ix_cooking_competency_evidence_competency_id'), table_name='cooking_competency_evidence')
    op.drop_table('cooking_competency_evidence')
    op.drop_index(op.f('ix_kitchen_meal_plans_user_id'), table_name='kitchen_meal_plans')
    op.drop_index(op.f('ix_kitchen_meal_plans_status'), table_name='kitchen_meal_plans')
    op.drop_index(op.f('ix_kitchen_meal_plans_shopping_action_id'), table_name='kitchen_meal_plans')
    op.drop_index(op.f('ix_kitchen_meal_plans_recommendation_option_id'), table_name='kitchen_meal_plans')
    op.drop_index(op.f('ix_kitchen_meal_plans_recommendation_id'), table_name='kitchen_meal_plans')
    op.drop_index(op.f('ix_kitchen_meal_plans_recipe_id'), table_name='kitchen_meal_plans')
    op.drop_index(op.f('ix_kitchen_meal_plans_planned_for'), table_name='kitchen_meal_plans')
    op.drop_index(op.f('ix_kitchen_meal_plans_meal_history_id'), table_name='kitchen_meal_plans')
    op.drop_index(op.f('ix_kitchen_meal_plans_idempotency_key'), table_name='kitchen_meal_plans')
    op.drop_index(op.f('ix_kitchen_meal_plans_cooking_action_id'), table_name='kitchen_meal_plans')
    op.drop_table('kitchen_meal_plans')
    op.drop_index(op.f('ix_finance_transactions_user_id'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_source'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_receipt_import_id'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_occurred_on'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_merchant_id'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_import_batch_id'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_fingerprint'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_external_id'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_direction'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_currency'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_category_id'), table_name='finance_transactions')
    op.drop_table('finance_transactions')
    op.drop_index(op.f('ix_receipt_imports_user_id'), table_name='receipt_imports')
    op.drop_index(op.f('ix_receipt_imports_transaction_at'), table_name='receipt_imports')
    op.drop_index(op.f('ix_receipt_imports_status'), table_name='receipt_imports')
    op.drop_index(op.f('ix_receipt_imports_merchant_id'), table_name='receipt_imports')
    op.drop_index(op.f('ix_receipt_imports_finance_transaction_id'), table_name='receipt_imports')
    op.drop_index(op.f('ix_receipt_imports_asset_id'), table_name='receipt_imports')
    op.drop_table('receipt_imports')
    op.drop_index(op.f('ix_finance_recurring_expenses_user_id'), table_name='finance_recurring_expenses')
    op.drop_index(op.f('ix_finance_recurring_expenses_status'), table_name='finance_recurring_expenses')
    op.drop_index(op.f('ix_finance_recurring_expenses_next_expected_on'), table_name='finance_recurring_expenses')
    op.drop_index(op.f('ix_finance_recurring_expenses_merchant_id'), table_name='finance_recurring_expenses')
    op.drop_index(op.f('ix_finance_recurring_expenses_category_id'), table_name='finance_recurring_expenses')
    op.drop_table('finance_recurring_expenses')
    op.drop_index(op.f('ix_finance_merchant_aliases_user_id'), table_name='finance_merchant_aliases')
    op.drop_index(op.f('ix_finance_merchant_aliases_normalized_alias'), table_name='finance_merchant_aliases')
    op.drop_index(op.f('ix_finance_merchant_aliases_merchant_id'), table_name='finance_merchant_aliases')
    op.drop_table('finance_merchant_aliases')
    op.drop_index(op.f('ix_finance_import_rows_user_id'), table_name='finance_import_rows')
    op.drop_index(op.f('ix_finance_import_rows_status'), table_name='finance_import_rows')
    op.drop_index(op.f('ix_finance_import_rows_review_required'), table_name='finance_import_rows')
    op.drop_index(op.f('ix_finance_import_rows_occurred_on'), table_name='finance_import_rows')
    op.drop_index(op.f('ix_finance_import_rows_merchant_id'), table_name='finance_import_rows')
    op.drop_index(op.f('ix_finance_import_rows_fingerprint'), table_name='finance_import_rows')
    op.drop_index(op.f('ix_finance_import_rows_direction'), table_name='finance_import_rows')
    op.drop_index(op.f('ix_finance_import_rows_category_id'), table_name='finance_import_rows')
    op.drop_index(op.f('ix_finance_import_rows_batch_id'), table_name='finance_import_rows')
    op.drop_table('finance_import_rows')
    op.drop_index(op.f('ix_kitchen_recipe_techniques_user_id'), table_name='kitchen_recipe_techniques')
    op.drop_index(op.f('ix_kitchen_recipe_techniques_technique_id'), table_name='kitchen_recipe_techniques')
    op.drop_index(op.f('ix_kitchen_recipe_techniques_recipe_id'), table_name='kitchen_recipe_techniques')
    op.drop_table('kitchen_recipe_techniques')
    op.drop_index(op.f('ix_kitchen_ingredient_aliases_user_id'), table_name='kitchen_ingredient_aliases')
    op.drop_index(op.f('ix_kitchen_ingredient_aliases_normalized_alias'), table_name='kitchen_ingredient_aliases')
    op.drop_index(op.f('ix_kitchen_ingredient_aliases_merchant'), table_name='kitchen_ingredient_aliases')
    op.drop_index(op.f('ix_kitchen_ingredient_aliases_ingredient_id'), table_name='kitchen_ingredient_aliases')
    op.drop_table('kitchen_ingredient_aliases')
    op.drop_index(op.f('ix_finance_merchants_user_id'), table_name='finance_merchants')
    op.drop_index(op.f('ix_finance_merchants_normalized_name'), table_name='finance_merchants')
    op.drop_index(op.f('ix_finance_merchants_default_category_id'), table_name='finance_merchants')
    op.drop_table('finance_merchants')
    op.drop_index(op.f('ix_finance_budgets_user_id'), table_name='finance_budgets')
    op.drop_index(op.f('ix_finance_budgets_month_start'), table_name='finance_budgets')
    op.drop_index(op.f('ix_finance_budgets_category_id'), table_name='finance_budgets')
    op.drop_index(op.f('ix_finance_budgets_active'), table_name='finance_budgets')
    op.drop_table('finance_budgets')
    op.drop_index(op.f('ix_cooking_competencies_user_id'), table_name='cooking_competencies')
    op.drop_index(op.f('ix_cooking_competencies_technique_id'), table_name='cooking_competencies')
    op.drop_table('cooking_competencies')
    op.drop_index(op.f('ix_media_assets_user_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_source'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_linked_entity_type'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_linked_entity_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_kind'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_deleted_at'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_content_hash'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_finance_import_batches_user_id'), table_name='finance_import_batches')
    op.drop_index(op.f('ix_finance_import_batches_status'), table_name='finance_import_batches')
    op.drop_index(op.f('ix_finance_import_batches_content_hash'), table_name='finance_import_batches')
    op.drop_table('finance_import_batches')
    op.drop_index(op.f('ix_finance_categories_user_id'), table_name='finance_categories')
    op.drop_index(op.f('ix_finance_categories_parent_id'), table_name='finance_categories')
    op.drop_index(op.f('ix_finance_categories_kind'), table_name='finance_categories')
    op.drop_index(op.f('ix_finance_categories_active'), table_name='finance_categories')
    op.drop_table('finance_categories')
    op.drop_index(op.f('ix_cooking_techniques_user_id'), table_name='cooking_techniques')
    op.drop_table('cooking_techniques')
    # ### end Alembic commands ###
